### ISSUE TITLE
Feature: Search all tabs and panes (from the current session only)

### ISSUE THREAD

**Issue by webgefrickel** [andersevenrud/cmp-tmux#17]
First and foremost: thanks a lot for this awesome cmp-plugin :) I just made the switch from 'the old vim' to neovim and am quite happy about this.

One idea though: currently when I activate the option `all_panes = true` everything works as expected, but feels kinda sluggish and slow. I usually work on a few projects at a time, all in their own tmux-session (including mutt/office stuff and my dotfiles of course). 

Would it be feasible to also add an option in the likes of `session_panes_only = true`, as an in-between option so to say? The idea would be that I have autocompletion from the current session and its contents, but not from other sessions attached (e.g. I don't need autocompletion from my dotfiles in customer-projects). As far as I've looked into it, there is no easy flag (as the -a for all_panes) in tmux to achieve this. I hope that it would react a bit faster, if there is less content to autocomplete from, but I have no idea if that would achieve this goal.

I am quite new to neovim and lua, I can give it a shot, maybe over the holidays. Would a PR for this be welcome?

**Comment by andersevenrud** [comment]
Hi!

> As far as I've looked into it, there is no easy flag (as the -a for all_panes) in tmux to achieve this

I just looked at this as well, and indeed, there is no way to do this, really :thinking: 

> Would a PR for this be welcome?

Sure. If you can find a way to solve this, then I'd love a RP on it :)

Might be worth looking at other optimizations as well. Maybe there's a way to do some light caching or look at executing stuff as a Job.

**Comment by andersevenrud** [comment]
Maybe adding a selection dialog for the user could help out with this ?

My thought here is to add a selection dialog (which should be in 0.6) to select what tmux buffers should be used :thinking:

**Comment by andersevenrud** [comment]
Also, for performance it could be worth investigating `vim.schedule` to prevent blocking of the thread.

**Comment by andersevenrud** [comment]
Could you try the following branch to see if it helps with performance ? 

https://github.com/andersevenrud/cmp-tmux/pull/20

**Comment by webgefrickel** [comment]
Hello @andersevenrud,

Happy new year! Sorry for the delay—I was afk over the holidays. 

Your PR (at least for me) made things waaay more responsive. I would consider this issue fixed!

Thanks a lot :)

**Comment by andersevenrud** [comment]
Happy new year @webgefrickel !

Glad to get some confirmation on that. I was unable to get numbers on it, but I noticed quite a bump in performance myself :)

> I would consider this issue fixed!

Then I'll go ahead and close it.
