### ISSUE TITLE
keyword_pattern didn't work

### ISSUE THREAD

**Issue by Karmenzind** [andersevenrud/cmp-tmux#27]
my configuration ([the whole file is here](https://github.com/Karmenzind/dotfiles-and-scripts/blob/master/home_k/.config/nvim/lua/config.lua#L153)):
```lua
cmp.setup({
    ...
    sources = {
        { name = "nvim_lsp" },
        { name = "ultisnips" },
        { name = "calc" },
        { name = "emoji" },
        { name = "tmux", option = { keyword_pattern = [[\w\w\w\+]] } },
    },
})

```

and `.` triggered:

![image](https://user-images.githubusercontent.com/17923071/197441192-c8506683-b5e2-4c96-9bd1-3c50fb7bf317.png)

**Comment by andersevenrud** [comment]
Try to set `trigger_characters = {}` instead.

**Comment by Congee** [comment]
> Try to set `trigger_characters = {}` instead.

That does not work either :sweat_smile:
