### ISSUE TITLE
Extension for nvim-cmp

### ISSUE THREAD

**Issue by gegoune** [andersevenrud/cmp-tmux#6]
I am not sure if you are aware on work in progress successor for nvim-compe, https://github.com/hrsh7th/nvim-cmp. Do you think you will be willing to support that plugin as well?

**Comment by andersevenrud** [comment]
I saw the news this morning. I'll add support for cmp as soon as I get a chance to test it out.

**Comment by andersevenrud** [comment]
Good news!

I have migrated over to cmp in this branch: https://github.com/andersevenrud/compe-tmux/pull/7

So if you've switched feel free to take it for a spin. From my initial testing it seems to run just as expected :blush:

**Comment by andersevenrud** [comment]
I had to nuke the PR because apparently I can't change branches... and I wanted a shorter name.

So: https://github.com/andersevenrud/compe-tmux/pull/8

**Comment by gegoune** [comment]
Seems to be working fine except for label, which comes only as text and has no source label, as per your todo list. Thanks a lot!

**Comment by gegoune** [comment]
That adds label:

```lua
formatting = {
    vim_item.menu = ({
      tmux = '[tmuxytesty]',
    })[entry.source.name]

    return vim_item
  end,
},
```

**Comment by andersevenrud** [comment]
I finally got around to deprecate compe and update the branches :sweat_smile:
